name: Feature Branch

on:
  push:
    branches:
      - develop
jobs:

  create-prerelease:
    name: Create prerelease
    runs-on: ubuntu-18.04

    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          append_to_pre_release_tag: "dev"
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub prerelease
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Prerelease ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
